### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "NevisonTest11",
  "password": "Testing11",
  "email": "leenevison516@gmail.com"
}

###

### Login to get JWT
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "NevisonTest11",
  "password": "Testing11"
}

###

### Call protected route with JWT (replace token below after login)
GET http://localhost:3000/auth/profile
Authorization: Bearer 
