### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "NevisonTest3",
  "password": "Testing3",
  "email": "leenevison123@gmail.com"
}

###

### Login to get JWT
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "NevisonTest4",
  "password": "Testing3",
  "email": "leenevison123@gmail.com"
}

###

### Call protected route with JWT (replace token below after login)
GET http://localhost:3000/auth/profile
Authorization: Bearer 
